name: Website Deployment
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      # - name: Cache dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.bun/install/cache
      #     key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
      - name: Install Dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: bun i
      - name: Run ESLint
        id: run-lint
        run: bun run lint
      - name: Echo if lint failed
        if: ${{ failure() && steps.run-lint.outcome == 'failure' }}
        run: echo "Lint failed"
      - name: Echo if lint ok
        run: echo "Lint was successful"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
      - name: Install Dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: bun i

      - name: Test code
        run: bun test

  build:
    needs:
      - lint
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.find-js.outputs.script-file }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
      - name: Install Dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: bun i
      - name: Build Project
        run: bun run build
      - name: Publish JS filename
        id: find-js
        run: echo "script-file=$(find dist/assets/*.js -type f -execdir echo '{}' ';' | head -n 1)" >> $GITHUB_OUTPUT
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files # any name you like
          path: |
            dist
            public
            package.json

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files # same name as above for this example it should be `dist-files`
      - name: Output contents
        run: ls
      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying..."
